/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Quiz.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno Tarde
 */
public class Login_Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Login_Cadastro
     */
    public Login_Cadastro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        SenhaCadastro2 = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        SenhaCadastro1 = new javax.swing.JPasswordField();
        EmailCadastro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        SenhaLogin = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        NomeCadastro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        NomeLogin = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, -1, -1));

        jLabel11.setText("Esqueceu a senha?");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 304, -1, 20));
        getContentPane().add(SenhaCadastro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 420, 30));

        jLabel10.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirmar Senha:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));
        getContentPane().add(SenhaCadastro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 420, 30));
        getContentPane().add(EmailCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 420, 30));

        jLabel9.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));
        getContentPane().add(SenhaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 420, 30));

        jLabel8.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Senha:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));
        getContentPane().add(NomeCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 420, 30));

        jLabel7.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome do Usuario:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastro");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 338, 480, 20));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Logar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 300, 80, -1));

        jLabel6.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Senha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        getContentPane().add(NomeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 420, 30));

        jLabel5.setFont(new java.awt.Font("Swis721 Ex BT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome do Usuario:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao_imagens/LogoQuiz2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 390, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao_imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String VSenhaLogin=null;
        VSenhaLogin=(String.valueOf(SenhaLogin.getPassword()));
        if(NomeLogin.getText().equals("")||VSenhaLogin.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Login Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            Usuario usuario = new Usuario(NomeLogin.getText());
            usuario.setSenha(String.valueOf(SenhaLogin.getPassword()));
            if(Usuario.logar(usuario)){
                TelaTemas telaTemas= new TelaTemas();
                telaTemas.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Nome de usuario ou senha incorretos", "Login Incorreto", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String VSenhaCadastro1=null,VSenhaCadastro2=null;
        VSenhaCadastro1=(String.valueOf(SenhaCadastro1.getPassword()));
        VSenhaCadastro2=(String.valueOf(SenhaCadastro2.getPassword()));
        
        if(NomeCadastro.getText().equals("")||EmailCadastro.getText().equals("")||VSenhaCadastro1.equals("")||VSenhaCadastro2.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
        }else{
            String SenhaCadastro = null;
            Usuario usuario = new Usuario(NomeCadastro.getText());

            if(String.valueOf(SenhaCadastro1.getPassword()).equals(String.valueOf(SenhaCadastro2.getPassword()))){
            SenhaCadastro=(String.valueOf(SenhaCadastro1.getPassword()));         
            usuario.setSenha(String.valueOf(SenhaCadastro));
             usuario.setEmail(String.valueOf(EmailCadastro.getText()));
                if(Usuario.Cadastrar(usuario)){
                    TelaTemas telaTemas= new TelaTemas();
                    telaTemas.setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Esse nome de usuario ja existe", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Senhas diferentes", "Cadastro Incorreto", JOptionPane.WARNING_MESSAGE);
            }
           
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        RecupSenha recupSenha=new RecupSenha();
        recupSenha.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailCadastro;
    private javax.swing.JTextField NomeCadastro;
    private javax.swing.JTextField NomeLogin;
    private javax.swing.JPasswordField SenhaCadastro1;
    private javax.swing.JPasswordField SenhaCadastro2;
    private javax.swing.JPasswordField SenhaLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
