/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Quiz.Questionario;
import Quiz.Respostas;
import Quiz.Tema;
import java.util.ArrayList;
import javax.swing.ButtonGroup;

/**
 *
 * @author CLP
 */
public class TelaQuestoes extends javax.swing.JFrame {

    /**
     * Creates new form TelaQuestoes
     */
    
    private Tema tema;
    private int Correta;
    private Questionario questionario;
    private String r[]= new String[4];
    int i=0;

    
    public TelaQuestoes() {
        initComponents();
    }

    
    public TelaQuestoes(Tema tema) {
        initComponents();
        setLocationRelativeTo(null);
        bPerguntas = new ButtonGroup();
        
        bPerguntas.add(Op1);
        bPerguntas.add(Op2);
        bPerguntas.add(Op3);
        bPerguntas.add(Op4);
        
        bPerguntas.getSelection();
        
        
        this.tema = tema;
        ArrayList<Questionario> questoes = Questionario.questoesDoTema(tema);
        for (Questionario questao: questoes) {
            Pergunta.setText(questao.getDescricao());
            Correta=questao.getCorreta();
            this.Correta=Correta;
            questionario=new Questionario(questao.getId());
        }

        //ArrayList<Respostas> respostasDoTema(Tema tema,Questionario questionario)
        ArrayList<Respostas> respostas = Respostas.respostasDoTema(tema, questionario);
        for (Respostas resposta: respostas) {
            System.out.println(resposta.getDescricao());
            r[i]=resposta.getDescricao();      
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bPerguntas = new javax.swing.ButtonGroup();
        Op1 = new javax.swing.JRadioButton();
        Op2 = new javax.swing.JRadioButton();
        Op3 = new javax.swing.JRadioButton();
        Op4 = new javax.swing.JRadioButton();
        Pergunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Op1MouseClicked(evt);
            }
        });

        Op2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Op2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Op1)
                            .addComponent(Op4)
                            .addComponent(Op3)
                            .addComponent(Op2))
                        .addGap(0, 444, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pergunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Op1)
                .addGap(39, 39, 39)
                .addComponent(Op2)
                .addGap(36, 36, 36)
                .addComponent(Op3)
                .addGap(36, 36, 36)
                .addComponent(Op4)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Op1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Op1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Op1MouseClicked

    private void Op2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Op2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Op2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Op1;
    private javax.swing.JRadioButton Op2;
    private javax.swing.JRadioButton Op3;
    private javax.swing.JRadioButton Op4;
    private javax.swing.JLabel Pergunta;
    private javax.swing.ButtonGroup bPerguntas;
    // End of variables declaration//GEN-END:variables
}
